2025-10-02 12:22:31,223 - root - INFO - Logging configured successfully.
2025-10-02 12:22:31,223 - root - INFO - Log file created at: data/simulation_logs\simulation_20251002_122231.log
2025-10-02 12:22:31,224 - __main__ - INFO - Initializing Simulation (Layer 1)...
2025-10-02 12:22:31,224 - skymind_sim.layer_1_simulation.simulation - INFO - Simulation (Layer 1) initialized.
2025-10-02 12:22:31,224 - skymind_sim.layer_1_simulation.simulation - INFO - Attempting to load world from: data/maps/simple_map.json
2025-10-02 12:22:31,225 - __main__ - CRITICAL - An unhandled exception occurred: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "D:\Payannameh\SkyMind_Sim\skymind_sim\main.py", line 25, in main
    simulation.load_world_from_file('data/maps/simple_map.json')
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Payannameh\SkyMind_Sim\skymind_sim\layer_1_simulation\simulation.py", line 40, in load_world_from_file
    self.world = World(config['world_size']['width'], config['world_size']['height'])
                       ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
TypeError: list indices must be integers or slices, not str
2025-10-02 12:22:31,234 - __main__ - INFO - Application Closed
